folders:
  - "FENG"
  - "FFA"
  - "FHE"
  - "FMS"
  - "FSS_LAW_&_SPORT"
  - "FST"

heading_keywords:
  - "Explore Majors"
  - "Sample Career"
  - "Prospective"
  - "Skills And Characteristics"
  - "Alternative Career"
  - "Employers"
  - "Areas"
  - "Places that hire"
  - "What can I do"
  - "Skills Related"
  - "Sample Jobs"
  - "Sample"

font_styles:
  size: 14
  bold: true
  font: "Calibri"